export interface Badge {
    id: string;
    title: string;
    description: string;
    icon: string;
    color: string;
    xp: number;
    rarity: 'common' | 'rare' | 'epic' | 'legendary';
    category: 'budget' | 'savings' | 'investment' | 'subscription' | 'streak' | 'social';
    requirement: string;
    unlocked: boolean;
    unlockedAt?: string;
}

export const achievements: Badge[] = [
    // Budget Mastery
    {
        id: 'budget_ninja_1',
        title: 'Budget Ninja 🥷',
        description: 'Stayed under budget for 1 month',
        icon: '🥷',
        color: '#10B981',
        xp: 100,
        rarity: 'common',
        category: 'budget',
        requirement: 'Stay under budget for 1 consecutive month',
        unlocked: true,
        unlockedAt: '2024-12-01',
    },
    {
        id: 'budget_ninja_5',
        title: 'Budget Sensei 🎖️',
        description: 'Stayed under budget for 5 consecutive months',
        icon: '🎖️',
        color: '#3B82F6',
        xp: 500,
        rarity: 'epic',
        category: 'budget',
        requirement: 'Stay under budget for 5 consecutive months',
        unlocked: true,
        unlockedAt: '2024-12-15',
    },
    {
        id: 'budget_master',
        title: 'Budget Master 👑',
        description: 'Stayed under budget for 12 consecutive months',
        icon: '👑',
        color: '#A78BFA',
        xp: 1500,
        rarity: 'legendary',
        category: 'budget',
        requirement: 'Stay under budget for 12 consecutive months',
        unlocked: false,
    },

    // Savings Streaks
    {
        id: 'savings_starter',
        title: 'Savings Starter 💰',
        description: 'Saved money for 7 consecutive days',
        icon: '💰',
        color: '#10B981',
        xp: 150,
        rarity: 'common',
        category: 'savings',
        requirement: 'Save money daily for 7 days',
        unlocked: true,
        unlockedAt: '2024-11-20',
    },
    {
        id: 'savings_champion',
        title: 'Savings Champion 🏆',
        description: 'Saved money for 30 consecutive days',
        icon: '🏆',
        color: '#F59E0B',
        xp: 750,
        rarity: 'epic',
        category: 'savings',
        requirement: 'Save money daily for 30 days',
        unlocked: false,
    },
    {
        id: 'savings_legend',
        title: 'Savings Legend 💎',
        description: 'Saved money for 100 consecutive days',
        icon: '💎',
        color: '#8B5CF6',
        xp: 2500,
        rarity: 'legendary',
        category: 'savings',
        requirement: 'Save money daily for 100 days',
        unlocked: false,
    },

    // Investment Journey
    {
        id: 'investment_explorer',
        title: 'Investment Explorer 🌱',
        description: 'Made your first SIP investment',
        icon: '🌱',
        color: '#10B981',
        xp: 200,
        rarity: 'rare',
        category: 'investment',
        requirement: 'Make your first SIP investment',
        unlocked: false,
    },
    {
        id: 'portfolio_builder',
        title: 'Portfolio Builder 📈',
        description: 'Invested in 3 different funds',
        icon: '📈',
        color: '#3B82F6',
        xp: 500,
        rarity: 'epic',
        category: 'investment',
        requirement: 'Invest in 3 different mutual funds',
        unlocked: false,
    },
    {
        id: 'wealth_creator',
        title: 'Wealth Creator 🚀',
        description: 'Investment portfolio crossed ₹1 Lakh',
        icon: '🚀',
        color: '#A78BFA',
        xp: 1000,
        rarity: 'legendary',
        category: 'investment',
        requirement: 'Build investment portfolio worth ₹1,00,000',
        unlocked: false,
    },

    // Subscription Management
    {
        id: 'subscription_slayer_1',
        title: 'Subscription Slayer ⚔️',
        description: 'Cancelled 1 unused subscription',
        icon: '⚔️',
        color: '#F59E0B',
        xp: 100,
        rarity: 'common',
        category: 'subscription',
        requirement: 'Cancel 1 unused subscription',
        unlocked: true,
        unlockedAt: '2024-11-10',
    },
    {
        id: 'subscription_slayer_3',
        title: 'Subscription Warrior 🗡️',
        description: 'Cancelled 3 unused subscriptions',
        icon: '🗡️',
        color: '#EF4444',
        xp: 300,
        rarity: 'rare',
        category: 'subscription',
        requirement: 'Cancel 3 unused subscriptions',
        unlocked: false,
    },
    {
        id: 'subscription_destroyer',
        title: 'Subscription Destroyer 💣',
        description: 'Cancelled 10 unused subscriptions',
        icon: '💣',
        color: '#DC2626',
        xp: 1000,
        rarity: 'epic',
        category: 'subscription',
        requirement: 'Cancel 10 unused subscriptions',
        unlocked: false,
    },

    // Streak Achievements
    {
        id: 'daily_tracker_7',
        title: 'Daily Tracker 📱',
        description: 'Logged in 7 days in a row',
        icon: '📱',
        color: '#3B82F6',
        xp: 150,
        rarity: 'common',
        category: 'streak',
        requirement: 'Log in for 7 consecutive days',
        unlocked: true,
        unlockedAt: '2024-12-10',
    },
    {
        id: 'daily_tracker_30',
        title: 'Consistency King 👑',
        description: 'Logged in 30 days in a row',
        icon: '👑',
        color: '#F59E0B',
        xp: 750,
        rarity: 'epic',
        category: 'streak',
        requirement: 'Log in for 30 consecutive days',
        unlocked: false,
    },
    {
        id: 'daily_tracker_100',
        title: 'Legendary Streak 🔥',
        description: 'Logged in 100 days in a row',
        icon: '🔥',
        color: '#DC2626',
        xp: 3000,
        rarity: 'legendary',
        category: 'streak',
        requirement: 'Log in for 100 consecutive days',
        unlocked: false,
    },

    // Social Achievements
    {
        id: 'social_butterfly',
        title: 'Social Butterfly 🦋',
        description: 'Joined your first savings challenge',
        icon: '🦋',
        color: '#EC4899',
        xp: 200,
        rarity: 'rare',
        category: 'social',
        requirement: 'Join a group savings challenge',
        unlocked: false,
    },
    {
        id: 'team_player',
        title: 'Team Player 🤝',
        description: 'Completed a group challenge with friends',
        icon: '🤝',
        color: '#8B5CF6',
        xp: 500,
        rarity: 'epic',
        category: 'social',
        requirement: 'Complete a group savings challenge',
        unlocked: false,
    },
    {
        id: 'leaderboard_champion',
        title: 'Leaderboard Champion 🥇',
        description: 'Reached #1 on friend leaderboard',
        icon: '🥇',
        color: '#F59E0B',
        xp: 1000,
        rarity: 'legendary',
        category: 'social',
        requirement: 'Reach #1 on friend leaderboard',
        unlocked: false,
    },

    // Special Milestones
    {
        id: 'first_transaction',
        title: 'First Step 👣',
        description: 'Added your first transaction',
        icon: '👣',
        color: '#10B981',
        xp: 50,
        rarity: 'common',
        category: 'budget',
        requirement: 'Add your first transaction',
        unlocked: true,
        unlockedAt: '2024-10-01',
    },
    {
        id: 'transaction_logger_50',
        title: 'Transaction Pro 📝',
        description: 'Logged 50 transactions',
        icon: '📝',
        color: '#3B82F6',
        xp: 300,
        rarity: 'rare',
        category: 'budget',
        requirement: 'Log 50 transactions',
        unlocked: true,
        unlockedAt: '2024-11-15',
    },
    {
        id: 'transaction_logger_500',
        title: 'Transaction Master 📚',
        description: 'Logged 500 transactions',
        icon: '📚',
        color: '#A78BFA',
        xp: 1500,
        rarity: 'epic',
        category: 'budget',
        requirement: 'Log 500 transactions',
        unlocked: false,
    },

    // Savings Milestones (Extended)
    {
        id: 'emergency_ready',
        title: 'Emergency Ready 🛡️',
        description: 'Saved ₹10,000 in your Emergency Fund',
        icon: '🛡️',
        color: '#10B981',
        xp: 250,
        rarity: 'rare',
        category: 'savings',
        requirement: 'Reach ₹10,000 in Emergency Fund',
        unlocked: false,
    },
    {
        id: 'frugal_master',
        title: 'Frugal Master 🧘',
        description: 'Spent less than 50% of your income this month',
        icon: '🧘',
        color: '#3B82F6',
        xp: 400,
        rarity: 'epic',
        category: 'budget',
        requirement: 'Keep spending below 50% of monthly income',
        unlocked: false,
    },
    {
        id: 'debt_destroyer',
        title: 'Debt Destroyer 🧨',
        description: 'Cleared all high-interest debt',
        icon: '🧨',
        color: '#EF4444',
        xp: 1000,
        rarity: 'legendary',
        category: 'budget',
        requirement: 'Pay off all credit card or high-interest debt',
        unlocked: false,
    },

    // Investment Mastery
    {
        id: 'dividend_collector',
        title: 'Dividend Collector 🪙',
        description: 'Received your first dividend payout',
        icon: '🪙',
        color: '#F59E0B',
        xp: 300,
        rarity: 'rare',
        category: 'investment',
        requirement: 'Receive a dividend from investments',
        unlocked: false,
    },
    {
        id: 'index_investor',
        title: 'Index Investor 📊',
        description: 'Invested in an Index Fund/ETF',
        icon: '📊',
        color: '#10B981',
        xp: 200,
        rarity: 'common',
        category: 'investment',
        requirement: 'Make an investment in an index fund',
        unlocked: false,
    },
    {
        id: 'diversification_king',
        title: 'Diversification King 🧿',
        description: 'Invested in 5+ different asset classes',
        icon: '🧿',
        color: '#8B5CF6',
        xp: 800,
        rarity: 'epic',
        category: 'investment',
        requirement: 'Own investments in 5 different asset classes',
        unlocked: false,
    },

    // Advanced Budgeting
    {
        id: 'category_czar_food',
        title: 'Dining Diplomat 🥗',
        description: 'Stayed under Food budget for 3 months',
        icon: '🥗',
        color: '#F59E0B',
        xp: 350,
        rarity: 'rare',
        category: 'budget',
        requirement: 'Stay under Food & Dining budget for 3 consecutive months',
        unlocked: false,
    },
    {
        id: 'category_czar_shopping',
        title: 'Shopping Stoic 🧥',
        description: 'Zero spending on Shopping for a full month',
        icon: '🧥',
        color: '#EC4899',
        xp: 500,
        rarity: 'epic',
        category: 'budget',
        requirement: 'No shopping transactions for 30 days',
        unlocked: false,
    },

    // Subscription Efficiency
    {
        id: 'audit_expert',
        title: 'Audit Expert 🔍',
        description: 'Reviewed all subscriptions this month',
        icon: '🔍',
        color: '#3B82F6',
        xp: 150,
        rarity: 'common',
        category: 'subscription',
        requirement: 'Complete a subscription audit in the app',
        unlocked: false,
    },
    {
        id: 'family_plan_pro',
        title: 'Family Plan Pro 👨‍👩‍👧',
        description: 'Switched to a family plan to save money',
        icon: '👨‍👩‍👧',
        color: '#10B981',
        xp: 200,
        rarity: 'rare',
        category: 'subscription',
        requirement: 'Mark a subscription as Family Shared',
        unlocked: false,
    },

    // Extreme Streaks
    {
        id: ' streak_warrior_365',
        title: 'Year of Wisdom 🪐',
        description: 'Logged in for 365 days in a row',
        icon: '🪐',
        color: '#A78BFA',
        xp: 10000,
        rarity: 'legendary',
        category: 'streak',
        requirement: 'Log in for 365 consecutive days',
        unlocked: false,
    },
    {
        id: 'weekend_warrior',
        title: 'Weekend Warrior ⚔️',
        description: 'Avoided spending on 4 consecutive weekends',
        icon: '⚔️',
        color: '#3B82F6',
        xp: 600,
        rarity: 'epic',
        category: 'streak',
        requirement: 'Zero discretionary spending on 4 consecutive weekends',
        unlocked: false,
    },

    // Social & Community
    {
        id: 'challenge_leader',
        title: 'Challenge Leader 📢',
        description: 'Created your first group savings challenge',
        icon: '📢',
        color: '#8B5CF6',
        xp: 400,
        rarity: 'rare',
        category: 'social',
        requirement: 'Create a group challenge and invite at least 3 friends',
        unlocked: false,
    },
    {
        id: 'wealth_mentor',
        title: 'Wealth Mentor 🎓',
        description: 'Shared 10 financial insights with friends',
        icon: '🎓',
        color: '#10B981',
        xp: 500,
        rarity: 'epic',
        category: 'social',
        requirement: 'Share app insights 10 times',
        unlocked: false,
    },

    // Large Milestones
    {
        id: 'half_lakh_club',
        title: 'Half Lakh Club 📈',
        description: 'Total savings crossed ₹50,000',
        icon: '📈',
        color: '#3B82F6',
        xp: 1000,
        rarity: 'epic',
        category: 'savings',
        requirement: 'Total app savings reach ₹50,000',
        unlocked: false,
    },
    {
        id: 'millennial_millionaire_1',
        title: 'First Lakh 🥇',
        description: 'Total savings crossed ₹1,00,000',
        icon: '🥇',
        color: '#F59E0B',
        xp: 2500,
        rarity: 'legendary',
        category: 'savings',
        requirement: 'Total app savings reach ₹1,00,000',
        unlocked: false,
    },

    // Behavioral
    {
        id: 'night_owl_saver',
        title: 'Night Owl Saver 🦉',
        description: 'Avoided late-night food orders for a month',
        icon: '🦉',
        color: '#1E293B',
        xp: 300,
        rarity: 'rare',
        category: 'budget',
        requirement: 'No food orders after 11 PM for 30 days',
        unlocked: false,
    },
    {
        id: 'manual_master',
        title: 'Manual Master ⌨️',
        description: 'Log 10 transactions within 5 mins of purchase',
        icon: '⌨️',
        color: '#3B82F6',
        xp: 200,
        rarity: 'common',
        category: 'budget',
        requirement: 'Add 10 transactions within 5 minutes of their timestamp',
        unlocked: false,
    },

    // Advanced Investment
    {
        id: 'rebalance_pro',
        title: 'Rebalance Pro ⚖️',
        description: 'Performed your first portfolio rebalance',
        icon: '⚖️',
        color: '#10B981',
        xp: 450,
        rarity: 'rare',
        category: 'investment',
        requirement: 'Rebalance your investment portfolio',
        unlocked: false,
    },
    {
        id: 'tax_optimizer',
        title: 'Tax Optimizer 📑',
        description: 'Invested in tax-saving ELSS funds',
        icon: '📑',
        color: '#3B82F6',
        xp: 500,
        rarity: 'epic',
        category: 'investment',
        requirement: 'Invest in any 80C specified instrument',
        unlocked: false,
    },

    // Engagement
    {
        id: 'feedback_friend',
        title: 'Feedback Friend 💬',
        description: 'Submitted your first app feedback',
        icon: '💬',
        color: '#10B981',
        xp: 100,
        rarity: 'common',
        category: 'social',
        requirement: 'Submit feedback via the settings menu',
        unlocked: false,
    },
    {
        id: 'app_ambassador',
        title: 'App Ambassador 🌟',
        description: 'Referred 5 friends to BudgetBandhu',
        icon: '🌟',
        color: '#F59E0B',
        xp: 1500,
        rarity: 'legendary',
        category: 'social',
        requirement: '5 successful friend sign-ups using your referral link',
        unlocked: false,
    },

    // Goals Specific
    {
        id: 'vacation_planner',
        title: 'Vacation Planner ✈️',
        description: 'Completed a Travel-related goal',
        icon: '✈️',
        color: '#3B82F6',
        xp: 500,
        rarity: 'rare',
        category: 'savings',
        requirement: 'Complete any goal categorized under Travel',
        unlocked: false,
    },
    {
        id: 'house_hunter',
        title: 'Future Homeowner 🏡',
        description: 'Saved 10% of your Home Downpayment goal',
        icon: '🏡',
        color: '#10B981',
        xp: 1000,
        rarity: 'epic',
        category: 'savings',
        requirement: 'Reach 10% progress on a Home Downpayment goal',
        unlocked: false,
    },

    // Tech Savvy
    {
        id: 'voice_commander',
        title: 'Voice Commander 🎙️',
        description: 'Added 10 transactions using voice input',
        icon: '🎙️',
        color: '#8B5CF6',
        xp: 300,
        rarity: 'rare',
        category: 'budget',
        requirement: 'Use voice input for 10 transaction entries',
        unlocked: false,
    },
    {
        id: 'api_connector',
        title: 'Bank Sync Pro 🔄',
        description: 'Synced your first bank account',
        icon: '🔄',
        color: '#3B82F6',
        xp: 500,
        rarity: 'rare',
        category: 'budget',
        requirement: 'Successfully connect a bank account via API sync',
        unlocked: false,
    },

    // Miscellaneous
    {
        id: 'early_adopter',
        title: 'Early Adopter 🚀',
        description: 'Joined during the beta phase',
        icon: '🚀',
        color: '#F59E0B',
        xp: 1000,
        rarity: 'legendary',
        category: 'social',
        requirement: 'Create an account during the first 30 days of app launch',
        unlocked: true,
        unlockedAt: '2024-10-01',
    },
    {
        id: 'dark_mode_lover',
        title: 'Night Vision 🌙',
        description: 'Used the app in dark mode for a week',
        icon: '🌙',
        color: '#1E293B',
        xp: 50,
        rarity: 'common',
        category: 'social',
        requirement: 'Keep dark mode active for 7 consecutive days',
        unlocked: false,
    },
    {
        id: 'notification_ninja',
        title: 'Stay Informed 🔔',
        description: 'Enabled all budget alerts',
        icon: '🔔',
        color: '#10B981',
        xp: 50,
        rarity: 'common',
        category: 'budget',
        requirement: 'Turn on all available budget notifications',
        unlocked: false,
    },
    {
        id: 'privacy_pro',
        title: 'Privacy Pro 🔒',
        description: 'Enabled biometric lock',
        icon: '🔒',
        color: '#3B82F6',
        xp: 200,
        rarity: 'rare',
        category: 'social',
        requirement: 'Enable Fingerprint or FaceID app lock',
        unlocked: false,
    },
    {
        id: 'streak_saver_pro',
        title: 'Streak Saver 🛡️',
        description: 'Used a streak freeze to keep progress',
        icon: '🛡️',
        color: '#EC4899',
        xp: 100,
        rarity: 'rare',
        category: 'streak',
        requirement: 'Apply a "Streak Freeze" item from the shop',
        unlocked: false,
    },
];

export const getRarityColor = (rarity: Badge['rarity']) => {
    switch (rarity) {
        case 'common': return '#10B981';
        case 'rare': return '#3B82F6';
        case 'epic': return '#A78BFA';
        case 'legendary': return '#F59E0B';
    }
};
